from sqlalchemy import select, func, or_
from sqlalchemy.orm import Session
from app.models import PromptTemplate, Context, Post, SocialAccount, Task
from app.models import Post, User, Workspace, WorkspaceMember, Notifications
from app.security import hash_password, hash_pin




def get_user_by_email(db: Session, email: str) -> User | None:
    return db.scalar(select(User).where(User.email == email))


def get_user_by_username(db: Session, username: str) -> User | None:
    return db.scalar(select(User).where(User.username == username))


def get_workspace_by_id(db: Session, workspace_id: str) -> Workspace | None:
    return db.get(Workspace, workspace_id)


def _build_user(*, username: str, email: str, password: str, account_type: str) -> User:
    return User(
        username=username,
        email=email,
        password_hash=hash_password(password),
        account_type=account_type,
        is_email_verified=True,
    )


def create_individual_user(db: Session, *, username: str, email: str, password: str) -> User:
    """Personal (individual) account: plain user, no workspace involved."""
    user = _build_user(username=username, email=email, password=password, account_type="individual")
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


def create_manager_with_workspace(
    db: Session,
    *,
    username: str,
    email: str,
    password: str,
    workspace_name: str,
    workspace_pin: str,
) -> tuple[User, Workspace]:
    """
    Business account, role=manager: creates the user AND a brand-new
    workspace in the same transaction, with the user as its manager.
    workspace_uuid is generated by the DB (public.generate_workspace_id()).
    """
    user = _build_user(username=username, email=email, password=password, account_type="business")
    db.add(user)
    db.flush()  # assigns user.users_uuid without committing yet

    workspace = Workspace(
        workspacename=workspace_name,
        manager_id=user.users_uuid,
        pin_hash=hash_pin(workspace_pin),
    )
    db.add(workspace)

    db.commit()
    db.refresh(user)
    db.refresh(workspace)
    return user, workspace


def create_member_for_workspace(
    db: Session,
    *,
    username: str,
    email: str,
    password: str,
    workspace: Workspace,
) -> User:
    """
    Business account, role=member: creates the user AND attaches them as an
    active member of an already-validated workspace, in the same transaction.
    """
    user = _build_user(username=username, email=email, password=password, account_type="business")
    db.add(user)
    db.flush()  # assigns user.users_uuid without committing yet

    membership = WorkspaceMember(
        user_id=user.users_uuid,
        workspace_id=workspace.workspace_uuid,
        status="active",
    )
    db.add(membership)

    db.commit()
    db.refresh(user)
    return user


def derive_role(db: Session, user: User) -> str:
    manages = db.scalar(select(Workspace.workspace_uuid).where(Workspace.manager_id == user.users_uuid))
    if manages is not None:
        return "manager"

    is_member = db.scalar(
        select(WorkspaceMember.workspace_id).where(
            WorkspaceMember.user_id == user.users_uuid,
            WorkspaceMember.status == "active",
        )
    )
    if is_member is not None:
        return "member"

    return "individual"

def list_workspace_members(db: Session, workspace_id: str) -> list[WorkspaceMember]:
    return db.scalars(
        select(WorkspaceMember)
        .where(WorkspaceMember.workspace_id == workspace_id, WorkspaceMember.status == "active")
    ).all()

def count_workspace_members(db: Session, workspace_id: str) -> int:
    return db.scalar(
        select(func.count()).select_from(WorkspaceMember)
        .where(WorkspaceMember.workspace_id == workspace_id, WorkspaceMember.status == "active")
    ) or 0

def list_distributors(db: Session, workspace_id: str) -> list[SocialAccount]:
    return db.scalars(
        select(SocialAccount).where(SocialAccount.workspace_id == workspace_id)
    ).all()

def list_posts_for_role(db: Session, workspace_id: str, user_id, role: str) -> list[Post]:
    query = select(Post).where(Post.workspace_id == workspace_id)
    if role == "member":
        query = query.where(Post.author_id == user_id)
    return db.scalars(query.order_by(Post.created_at.desc())).all()

def list_posts_for_user(db: Session, user_id) -> list[Post]:
    return db.scalars(
        select(Post).where(Post.author_id == user_id).order_by(Post.created_at.desc())
    ).all()

def list_tasks_for_role(db: Session, workspace_id: str, user_id, role: str) -> list[Task]:
    query = select(Task).where(Task.workspace_id == workspace_id)
    if role == "member":
         query = query.where(Task.assigned_to == user_id)
    return db.scalars(query.order_by(Task.created_at.desc())).all()

def get_post_by_id(db: Session, post_id, workspace_id: str) -> Post | None:
    return db.scalar(select(Post).where(Post.id == post_id, Post.workspace_id == workspace_id))

def create_task(
    db: Session, *, workspace_id: str, title: str,
    content: str, priority: str, assigned_to, created_by, due_date=None,
) -> Task:
    task = Task(
        workspace_id=workspace_id, title=title, content=content,
        priority=priority, assigned_to=assigned_to, created_by=created_by,
        due_date=due_date,
    )
    db.add(task)
    db.flush()
    create_task_notification(db, task)
    db.commit()
    db.refresh(task)
    return task

def update_post(db: Session, post: Post, updates: dict) -> Post:
    for field, value in updates.items():
        setattr(post, field, value)
    db.commit()
    db.refresh(post)
    return post

def update_distributor(db: Session, account: SocialAccount, updates: dict) -> SocialAccount:
    for field, value in updates.items():
        setattr(account, field, value)
    db.commit()
    db.refresh(account)
    return account

def update_task(db: Session, task: Task, updates: dict) -> Task:
    for field, value in updates.items():
        setattr(task, field, value)
    db.commit()
    db.refresh(task)
    return task

def soft_remove_member(db: Session, workspace_id: str, user_id) -> WorkspaceMember | None:
    membership = db.scalar(
        select(WorkspaceMember).where(
            WorkspaceMember.workspace_id == workspace_id,
            WorkspaceMember.user_id == user_id,
            WorkspaceMember.status == "active",
        )
    )
    if membership is None:
        return None 
    membership.status = "removed"
    membership.removed_at = func.now()
    db.commit()
    db.refresh(membership)
    return membership

def user_can_access_workspace(
    db: Session,
    *,
    user: User,
    workspace_id: str,
) -> bool:
    workspace = db.get(Workspace, workspace_id)

    if workspace is None:
        return False

    if workspace.manager_id == user.users_uuid:
        return True

    membership = db.scalar(
        select(WorkspaceMember).where(
            WorkspaceMember.workspace_id == workspace_id,
            WorkspaceMember.user_id == user.users_uuid,
            WorkspaceMember.status == "active",
        )
    )

    return membership is not None

def create_post(
    db: Session,
    *,
    author: User,
    workspace_id: str | None,
    title: str | None,
    content: str,
    prompt_template_id=None,
    knowledge_base_id=None,
    seo_keywords: list[str] | None = None,
    seo_hashtags: list[str] | None = None,
) -> Post:
    post = Post(
        workspace_id=workspace_id,
        author_id=author.users_uuid,
        title=title,
        content=content,
        status="draft",
        prompt_template_id=prompt_template_id,
        knowledge_base_id=knowledge_base_id,
        ai_generated=False,
        seo_keywords=seo_keywords,
        seo_hashtags=seo_hashtags,
    )

    db.add(post)
    db.commit()
    db.refresh(post)

    return post

def create_personal_task(
    db: Session, *, title: str, content: str, priority: str,
    assigned_to, created_by, due_date=None,
) -> Task:
    task = Task(
        workspace_id=None,
        title=title,
        content=content,
        priority=priority,
        assigned_to=created_by,
        created_by=created_by,
        due_date=due_date,
    )
    db.add(task)
    db.flush()
    create_task_notification(db, task)
    db.commit()
    db.refresh(task)
    return task

def list_calendar_tasks(db: Session, *, user_id) -> list[Task]:
    query = (
        select(Task)
        .where(or_(Task.created_by == user_id, Task.assigned_to == user_id))
        .order_by(Task.due_date.is_(None), Task.due_date.asc(), Task.created_at.desc())
    )
    return db.scalars(query).all()

def count_todo_tasks_for_user(db: Session, user_id) -> int:
    return db.scalar(
        select(func.count()).select_from(Task).where(
            Task.assigned_to == user_id,
            Task.status.notin_(["completed", "cancelled"]),
        )
    ) or 0

def count_tasks_assigned_to_others(db: Session, user_id) -> int:
    return db.scalar(
        select(func.count()).select_from(Task).where(
            Task.created_by == user_id,
            Task.assigned_to.isnot(None),
            Task.assigned_to != user_id,
            Task.status.notin_(["completed", "cancelled"]),
        )
    ) or 0

def create_task_notification(db: Session, task: Task):
    if task.assigned_to:
        notification = Notifications(
            user_id=task.assigned_to,
            task_id=task.id,
            type="task_assigned",
            message=f"Bạn được giao task mới: {task.title}"
        )
        db.add(notification)
        db.commit()

def count_unread_notifications(db: Session, users_id) -> int:
    return db.scalar(select(func.count()).select_from(Notifications).where(
        Notifications.user_id == users_id,
        Notifications.is_read.is_(False),
        )
    ) or 0

def list_notifications_for_user(db: Session, users_id, limit: int = 20) -> list[Notifications]:
    return db.scalar(select(Notifications).where(Notifications.user_id == users_id).order_by(Notifications.create_at.desc()).limit(limit)).all()

def mark_notification_read(db:Session, notifications_id, users_id) -> Notifications| None:
    notifications = db.scalar(select(Notifications).where(Notifications.id == notifications_id, Notifications.user_id == users_id))
    if notifications is None:
        return None
    notifications.is_read = True
    db.commit()
    db.refresh(notifications)
    return notifications

def mark_all_notifications_read(db: Session, users_id) -> int:
    notifications = db.scalars(
        select(Notifications).where(
            Notifications.user_id == users_id,
            Notifications.is_read.is_(False),
        )
    ).all()
    count = 0
    for n in notifications:
        n.is_read = True
        count += 1
    db.commit()
    return count

def create_due_soon_notification(db: Session, task: Task):
    if not task.assigned_to:
        return
    # Tránh tạo trùng nếu đã có notification due_soon cho task này rồi
    existing = db.scalar(
        select(Notifications).where(
            Notifications.task_id == task.id,
            Notifications.type == "due_soon",
        )
    )
    if existing:
        return
    notification = Notifications(
        user_id=task.assigned_to,
        task_id=task.id,
        type="due_soon",
        message=f"Task '{task.title}' sắp đến hạn",
    )
    db.add(notification)
    db.commit()


def get_tasks_due_soon(db: Session, hours: int = 24) -> list[Task]:
    from datetime import datetime, timedelta, timezone
    now = datetime.now(timezone.utc)
    threshold = now + timedelta(hours=hours)
    return db.scalars(
        select(Task).where(
            Task.due_date.isnot(None),
            Task.due_date <= threshold,
            Task.due_date >= now,
            Task.status.notin_(["completed", "cancelled"]),
        )
    ).all()

def create_prompt_template(
    db: Session,
    *,
    title: str,
    content: str,
    tags: list[dict] | None = None,
) -> PromptTemplate:
    template = PromptTemplate(
        title=title,
        content=content,
        tags=tags,
    )

    db.add(template)
    db.commit()
    db.refresh(template)

    return template


def list_prompt_templates(db: Session) -> list[PromptTemplate]:
    return db.scalars(
        select(PromptTemplate).order_by(PromptTemplate.created_at.desc())
    ).all()


def get_prompt_template_by_id(
    db: Session,
    template_id,
) -> PromptTemplate | None:
    return db.scalar(
        select(PromptTemplate).where(PromptTemplate.id == template_id)
    )


def update_prompt_template(
    db: Session,
    template: PromptTemplate,
    updates: dict,
) -> PromptTemplate:
    for field, value in updates.items():
        setattr(template, field, value)

    db.commit()
    db.refresh(template)

    return template


def create_context(
    db: Session,
    *,
    title: str,
    documents: list | None = None,
    tags: list[dict] | None = None,
) -> Context:
    context = Context(
        title=title,
        documents=documents,
        tags=tags,
    )

    db.add(context)
    db.commit()
    db.refresh(context)

    return context


def list_contexts(db: Session) -> list[Context]:
    return db.scalars(
        select(Context).order_by(Context.created_at.desc())
    ).all()


def get_context_by_id(
    db: Session,
    context_id,
) -> Context | None:
    return db.scalar(
        select(Context).where(Context.id == context_id)
    )


def update_context(
    db: Session,
    context: Context,
    updates: dict,
) -> Context:
    for field, value in updates.items():
        setattr(context, field, value)

    db.commit()
    db.refresh(context)

    return context