from sqlalchemy import select, func
from sqlalchemy.orm import Session
from app.models import Post, SocialAccount, Task

from app.models import User, Workspace, WorkspaceMember
from app.security import hash_password, hash_pin




def get_user_by_email(db: Session, email: str) -> User | None:
    return db.scalar(select(User).where(User.email == email))


def get_user_by_username(db: Session, username: str) -> User | None:
    return db.scalar(select(User).where(User.username == username))


def get_workspace_by_id(db: Session, workspace_id: str) -> Workspace | None:
    return db.get(Workspace, workspace_id)


def _build_user(*, username: str, email: str, password: str, account_type: str) -> User:
    return User(
        username=username,
        email=email,
        password_hash=hash_password(password),
        account_type=account_type,
    )


def create_individual_user(db: Session, *, username: str, email: str, password: str) -> User:
    """Personal (individual) account: plain user, no workspace involved."""
    user = _build_user(username=username, email=email, password=password, account_type="individual")
    db.add(user)
    db.commit()
    db.refresh(user)
    return user


def create_manager_with_workspace(
    db: Session,
    *,
    username: str,
    email: str,
    password: str,
    workspace_name: str,
    workspace_pin: str,
) -> tuple[User, Workspace]:
    """
    Business account, role=manager: creates the user AND a brand-new
    workspace in the same transaction, with the user as its manager.
    workspace_uuid is generated by the DB (public.generate_workspace_id()).
    """
    user = _build_user(username=username, email=email, password=password, account_type="business")
    db.add(user)
    db.flush()  # assigns user.users_uuid without committing yet

    workspace = Workspace(
        workspacename=workspace_name,
        manager_id=user.users_uuid,
        pin_hash=hash_pin(workspace_pin),
    )
    db.add(workspace)

    db.commit()
    db.refresh(user)
    db.refresh(workspace)
    return user, workspace


def create_member_for_workspace(
    db: Session,
    *,
    username: str,
    email: str,
    password: str,
    workspace: Workspace,
) -> User:
    """
    Business account, role=member: creates the user AND attaches them as an
    active member of an already-validated workspace, in the same transaction.
    """
    user = _build_user(username=username, email=email, password=password, account_type="business")
    db.add(user)
    db.flush()  # assigns user.users_uuid without committing yet

    membership = WorkspaceMember(
        user_id=user.users_uuid,
        workspace_id=workspace.workspace_uuid,
        status="active",
    )
    db.add(membership)

    db.commit()
    db.refresh(user)
    return user


def derive_role(db: Session, user: User) -> str:
    manages = db.scalar(select(Workspace.workspace_uuid).where(Workspace.manager_id == user.users_uuid))
    if manages is not None:
        return "manager"

    is_member = db.scalar(
        select(WorkspaceMember.workspace_id).where(
            WorkspaceMember.user_id == user.users_uuid,
            WorkspaceMember.status == "active",
        )
    )
    if is_member is not None:
        return "member"

    return "individual"

def list_workspace_members(db: Session, workspace_id: str) -> list[WorkspaceMember]:
    return db.scalars(
        select(WorkspaceMember)
        .where(WorkspaceMember.workspace_id == workspace_id, WorkspaceMember.status == "active")
    ).all()

def count_workspace_members(db: Session, workspace_id: str) -> int:
    return db.scalar(
        select(func.count()).select_from(WorkspaceMember)
        .where(WorkspaceMember.workspace_id == workspace_id, WorkspaceMember.status == "active")
    ) or 0

def list_distributors(db: Session, workspace_id: str) -> list[SocialAccount]:
    return db.scalars(
        select(SocialAccount).where(SocialAccount.workspace_id == workspace_id)
    ).all()

def list_posts_for_role(db: Session, workspace_id: str, user_id, role: str) -> list[Post]:
    query = select(Post).where(Post.workspace_id == workspace_id)
    if role == "member":
        query = query.where(Post.author_id == user_id)
    return db.scalars(query.order_by(Post.created_at.desc())).all()

def list_tasks_for_role(db: Session, workspace_id: str, user_id, role: str) -> list[Task]:
    query = select(Task).where(Task.workspace_id == workspace_id)
    if role == "member":
         query = query.where(Task.assigned_to == user_id)
    return db.scalars(query.order_by(Task.created_at.desc())).all()

def get_post_by_id(db: Session, post_id, workspace_id: str) -> Post | None:
    return db.scalar(select(Post).where(Post.id == post_id, Post.workspace_id == workspace_id))

def create_task(
    db: Session, *, workspace_id: str, title: str,
    content: str, priority: str, assigned_to,
) -> Task:
    task = Task(
        workspace_id=workspace_id, title=title, content=content,
        priority=priority, assigned_to=assigned_to,
    )
    db.add(task)
    db.commit()
    db.refresh(task)
    return task

def update_post(db: Session, post: Post, updates: dict) -> Post:
    for field, value in updates.items():
        setattr(post, field, value)
    db.commit()
    db.refresh(post)
    return post

def update_distributor(db: Session, account: SocialAccount, updates: dict) -> SocialAccount:
    for field, value in updates.items():
        setattr(account, field, value)
    db.commit()
    db.refresh(account)
    return account

def update_task(db: Session, task: Task, updates: dict) -> Task:
    for field, value in updates.items():
        setattr(task, field, value)
    db.commit()
    db.refresh(task)
    return task

def soft_remove_member(db: Session, workspace_id: str, user_id) -> WorkspaceMember | None:
    membership = db.scalar(
        select(WorkspaceMember).where(
            WorkspaceMember.workspace_id == workspace_id,
            WorkspaceMember.user_id == user_id,
            WorkspaceMember.status == "active",
        )
    )
    if membership is None:
        return None 
    membership.status = "removed"
    membership.removed_at = func.now()
    db.commit()
    db.refresh(membership)
    return membership
