import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum, ForeignKey, String, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

AccountType = Enum(
    "individual",
    "business",
    name="account_type_enum",
    schema="public",
    create_type=False,  
)

MembershipStatus = Enum(
    "pending",
    "active",
    "removed",
    name="membership_status_enum",
    schema="public",
    create_type=False,
)


class User(Base):

    __tablename__ = "users"
    __table_args__ = {"schema": "Users"}

    users_uuid: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    username: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    email: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(String, nullable=False)

    account_type: Mapped[str] = mapped_column(AccountType, nullable=False, server_default="individual")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    workspaces_managed: Mapped[list["Workspace"]] = relationship(back_populates="manager")
    memberships: Mapped[list["WorkspaceMember"]] = relationship(back_populates="user")


class Workspace(Base):

    __tablename__ = "workspaces"
    __table_args__ = {"schema": "workspaces"}

    # workspace_uuid is a 16-char code auto-generated by the DB function
    # public.generate_workspace_id() -- do not set it from Python, leave it unset
    # on insert so the server default kicks in.
    workspace_uuid: Mapped[str] = mapped_column(
        String(16), primary_key=True, server_default=text("public.generate_workspace_id()")
    )
    workspacename: Mapped[str] = mapped_column(String, nullable=False)
    manager_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("Users.users.users_uuid"), nullable=False)
    pin_hash: Mapped[str] = mapped_column(String, nullable=False, unique=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    manager: Mapped["User"] = relationship(back_populates="workspaces_managed")
    members: Mapped[list["WorkspaceMember"]] = relationship(back_populates="workspace")


class WorkspaceMember(Base):

    __tablename__ = "workspace_members"
    __table_args__ = {"schema": "workspaces"}

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("Users.users.users_uuid", ondelete="CASCADE"), primary_key=True
    )
    workspace_id: Mapped[str] = mapped_column(
        String(16), ForeignKey("workspaces.workspaces.workspace_uuid", ondelete="CASCADE"), primary_key=True
    )
    status: Mapped[str] = mapped_column(MembershipStatus, nullable=False, server_default="active")

    joined_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    removed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    user: Mapped["User"] = relationship(back_populates="memberships")
    workspace: Mapped["Workspace"] = relationship(back_populates="members")
